name: ElytraBooster
version: ${version}
main: com.github.jummes.elytrabooster.core.ElytraBooster
author: jummes
api-version: 1.13
commands:
  eb:
    description: Base ElytraBooster command
permissions:
  eb.admin.create:
    description: Booster creation permission
    default: op
  eb.admin.delete:
    description: Booster deletion permission
    default: op
  eb.admin.disable:
    description: Booster disabling permission
    default: op
  eb.admin.enable:
    description: Booster enabling permission
    default: op
  eb.admin.help:
    description: Show help message permission
    default: op
  eb.admin.list:
    description: List existing boosters permission
    default: op
  eb.admin.move:
    description: Booster moving permission
    default: op
  eb.admin.near:
    description: List near portals permission
    default: op
  eb.admin.reload:
    description: Reload plugin data permission
    default: op
  eb.admin.set:
    description: Set booster parameters
    default: op
  eb.boosters.boost:
    default: true
  eb.boosters.*:
    description: Wildcard booster usage permission
    default: true
    children:
      eb.boosters.boost: true
  eb.admin.*:
    description: Wildcard booster editing permission
    default: op
    children:
      eb.admin.create: true
      eb.admin.delete: true
      eb.admin.disable: true
      eb.admin.enable: true
      eb.admin.help: true
      eb.admin.list: true
      eb.admin.move: true
      eb.admin.near: true
      eb.admin.reload: true
      eb.admin.set: true
  eb.*:
    description: Wildcard ElytraBooster permission
    default: op
    children:
      eb.boosters.*: true
      eb.admin.*: true