name: ElytraBooster
version: ${version}
main: com.github.jummes.elytrabooster.core.ElytraBooster
author: jummes
api-version: 1.13
load: POSTWORLD
softdepend: [Multiverse-Core, MultiWorld]
commands:
  eb:
    description: Base ElytraBooster command
permissions:
  eb.admin.help:
    description: Show help message permission
    default: op
  eb.admin.modify:
    description: Modify booster permission
    default: op
  eb.admin.reload:
    description: Reload plugin data permission
    default: op
  eb.boosters.boost:
    default: true
  eb.boosters.*:
    description: Wildcard booster usage permission
    default: true
    children:
      eb.boosters.boost: true
  eb.admin.*:
    description: Wildcard booster editing permission
    default: op
    children:
      eb.admin.help: true
      eb.admin.modify: true
      eb.admin.reload: true
  eb.*:
    description: Wildcard ElytraBooster permission
    default: op
    children:
      eb.boosters.*: true
      eb.admin.*: true